### ISSUE TITLE
Small fixes

### ISSUE THREAD

**Issue by hustf** [Khanzi/Spotify.jl#22]
Obviously, there are some typos in the README. Also, dead code is strewn around. And why is there no way to use the PUT functions?

Maybe we can do something about this? I'm taking a new fork now.

**Comment by kwehmeyer** [comment]
I'll start working on the PUT functions and we can hunt down and dispose of dead code as we flesh out some other aspects of the package. If you see anything that isn't being used or is incomplete then just zap it.

**Comment by hustf** [comment]
Thanks for merging! A quick note for the follow-up: Manifest.toml places unnecessary constraints on the package system. Perhaps better to delete it? Also, in Project.toml, putting a lower bound on Julia at 1.6 may be beneficial. The menu thing is not part of the Spotify module, but it's simply better to use Julia 1.6 here, I think. Just an opinion.
