### ISSUE TITLE
Is this repo being actively maintained?

### ISSUE THREAD

**Issue by vnegi10** [Khanzi/Spotify.jl#24]
Hello,

First of all, please allow me to thank you for your hard work in creating this repository. I used it recently to analyze my Spotify data, and was extremely pleased with the results. It's great to see so much happening in the Julia community. I would also like to contribute in the following ways:
- Include more endpoints
- Improve documentation
- Register the package 

However, I noticed that it's been a while since the last commits were made. I would therefore like to know about your plans for the future of this repository.

Best regards,
Vikas

**Comment by kwehmeyer** [comment]
Hey Vikas, 

Thanks for reaching out, I haven't been able to work on this project for a while but I am very open to contributions. I am so happy to hear that you have found it useful.
Please feel free to contribute! You can open a PR and eventually I can add you as a contributor. If there is any way I can assist or any questions I can answer please just reach out. I plan on jumping back into this project soon and finish up some of the development points you have mentioned and would greatly appreciate help.

Cheers,
Kahlil

**Comment by vnegi10** [comment]
Hi Kahlil,

Thank you for the quick response. I am glad to hear that you plan to resume work on this project. I will start working on my proposed changes, and make a PR soon.

Best regards,
Vikas
