### ISSUE TITLE
Releases and Package Maintenance

### ISSUE THREAD

**Issue by kwehmeyer** [Khanzi/Spotify.jl#27]
Hey @vnegi10 
I checked out your other projects and noticed you have a lot more experience with building and release packages. I was hoping you and I can work together and tidy up this package. I started by installing a tag bot and registration bot to get the package out to more users. 

Do you think we could connect sometime, I would appreciate guidance and suggestions on moving the project maturity along.

**Comment by vnegi10** [comment]
Hi @kwehmeyer,

I have created only a couple of Julia packages, so I am still far from being an expert. That being said, I would be happy to share my experience. 

I saw that you already added `TagBot.yml` and updated `compat` entry in `Project.toml`. You will also need to add the registration bot to the repository. Check [here.](https://github.com/JuliaRegistries/Registrator.jl)

Once done, package registration can be initiated by commenting `@JuliaRegistrator register` on the latest commit. A pull request will be opened in the General Julia registry. Current waiting time is 3 days for new packages. Automatic checks will be carried out to verify if the minimum requirements are met. Apart from what's mentioned above, you also need:
- version entry in `Project.toml` --> OK
- LICENSE file --> OK

If all goes well, we should have a release of `v0.1.0.` After that, for every subsequent release, we only need to update the version number in `Project.toml` and comment to initiate new version registration (takes ~ 15-30 mins).

I have opened a PR with some updates. You can try to register the package after merging that. The project still needs a lot of work. As we make those improvements, we can keep on releasing new versions at regular intervals. I will continue with some more PRs (focusing on testing and documentation) in the coming days.

You can also connect with me on [LinkedIn.](https://www.linkedin.com/in/negivikas/)

**Comment by vnegi10** [comment]
Ignore the above message. It appeared because I added the registration tag in my earlier response, which triggered a registration attempt from here.
