### ISSUE TITLE
Building documentation

### ISSUE THREAD

**Issue by vnegi10** [Khanzi/Spotify.jl#30]
Hi @kwehmeyer,

Hope you are doing well. I am glad to see that we now have the package registered along with the first release.

I think the next step would be to create proper documentation. I have been adding docstrings as recommended [here.](https://docs.julialang.org/en/v1/manual/documentation/)

If you have time, could you try to build the document structure and add it to the repository? We can then deploy it to github pages, and include a badge in the README. See the **Documenting our Package** section in this excellent [guide.](https://syl1.gitbook.io/julia-language-a-concise-tutorial/language-core/11-developing-julia-packages)

Let me know in case you have other ideas.

**Comment by kwehmeyer** [comment]
Hey @vnegi10, have you heard of [JuliaDocs](https://juliadocs.github.io/Documenter.jl/stable/)? I think it would be a good candidate for building a docs repo for the package. Let me know what you think of this approach. Getting docs done is very high on my to-do list.

**Comment by vnegi10** [comment]
Hi @kwehmeyer, your link leads to `Documenter.jl`, which is also the approach mentioned in my earlier comment. I think we have the same idea. 

Using `Documenter.jl` and `DocumenterTools.jl`, the docstrings are rendered into html, which can be added to a dedicated `gh-pages` branch. Documentation build can be triggered when we make commits or release new versions via a `CI.yml` file. I have used this for my own packages, and it seems to work well.

**Comment by kwehmeyer** [comment]
Yep! I noticed that we had the same idea haha. I am working on drafting up some documentation now, see the branch I created. I will probably reach out to you if I end up getting stuck on the CI

**Comment by vnegi10** [comment]
haha, nice! I will check it out tomorrow. Off to bed now.

**Comment by kwehmeyer** [comment]
Initial documentation is completed. Visit it [here](https://kwehmeyer.github.io/Spotify.jl/dev/index.html)
