### ISSUE TITLE
Browser not opening during authentication

### ISSUE THREAD

**Issue by kwehmeyer** [Khanzi/Spotify.jl#34]
**Describe the bug**
Authentication browser window doesn't open on MacOS with Safari 

**To Reproduce**
1. On MacOS with only Safari installed attempt to authenticate

**Expected behavior**
Browser should open prompting user to allow Application access to user data

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS Monterey
 - Browser safari

**Additional context**
It looks like the methods for calling and getting the safari path is incorrect. Will require a code change and update in [`open_a_browser.jl`](https://github.com/kwehmeyer/Spotify.jl/blob/master/src/authorization/open_a_browser.jl)

**Comment by kwehmeyer** [comment]
@hustf is this something we could work on together?

**Comment by hustf** [comment]
Hi, I'm afraid my Mac is packed down at the moment, and the original command string is perhaps five years old. 
It would be a trial and error excercise for me to find the updated command string. Good luck!

**Comment by vnegi10** [comment]
Hey @kwehmeyer, I tested on a MacBook Air with Big Sur, and the authentication window opens on Safari (not automatically though, you need to click on the link which is the same as on my Linux system). All tests are also okay as expected. 

Is this issue specific to Monterey?

**Comment by kwehmeyer** [comment]
@vnegi10 Hmm the browser should open automatically. That's the issue. I am on Monterey and It's the same process as what you've described.

`open -a safari`
will open safari via the `zsh` command. May just have to modify for Mac specifically. Also the current code searches for `safari.exe` which does not make sense to me. I will have to revisit it https://github.com/kwehmeyer/Spotify.jl/blob/master/src/authorization/open_a_browser.jl

**Comment by kwehmeyer** [comment]
@vnegi10 I think I found the issue. Will open a PR soon. I will need to clean up some of the code. but for the time being just know that I was able to have it automatically open safari on the right web page. I will need to run a VM and verify that it works on windows as well
