### ISSUE TITLE
How to improve code coverage?

### ISSUE THREAD

**Issue by vnegi10** [Khanzi/Spotify.jl#37]
Hey @kwehmeyer, I was wondering about the code coverage metric being too low. I don't have much experience with it, but from what I understand, it should measure the % of code covered with our tests. I would expect that to be rather high, maybe even > 50% if we run all the tests.

I see that you have added the action `- uses: codecov/codecov-action@v1` to **builddoc.yml** and not a separate **CI.yml** file. Could it be that current code coverage is somehow only measuring the documentation?

**Comment by kwehmeyer** [comment]
I am also not aquatinted with Codecov metrics. However, when viewing the report it does seem to be look at the whole repo source code. Not sure if adding a CI to build and run tests would adjust those metrics but I will look into it!

**Comment by kwehmeyer** [comment]
@vnegi10 I added CI for ubuntu, macOS, and windows. Looks like a good portion of our tests are failing. I will dig into it more in the morning but I suspect that the CI can't authenticate and therefore all the tests are failing. I wonder if we can manage a workaround.

**Comment by vnegi10** [comment]
@kwehmeyer, I found a way to generate basic code coverage metrics using the `Coverage.jl` package. See my latest PR.

You can execute the `code_coverage.jl` script while on your local master, and the result should appear (see screenshot below) in the REPL. A `lcov.info` file is also written (excluded from my PR), which I think can be manually uploaded to Codecov.

Since we need client credentials to run most of the tests, I think we can use the following way of working:
- Before requesting new version release, run `code_coverage.jl` on latest local master
- Upload reports to Codecov
- Now request new version

Tip: In case you use VS Code, there's a cool extension called **Coverage Gutters** (by ryanluker), which allows for visualization of coverage within each file.

![Screenshot from 2021-11-13 14-33-22](https://user-images.githubusercontent.com/68782261/141645792-3d5e3f0b-5fc1-4a18-9530-d2205a6c9415.png)

**Comment by kwehmeyer** [comment]
@vnegi10 I think that's a reasonable workaround. I've removed the codecov actions and the badge. I will see if I can find a way to do the tests automated but for the time doing I think a local pre-release run is probably the only way to go.
